# Generated by Django 3.2.4 on 2021-09-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
